### ISSUE TITLE
GetDownloadUrlAsync return null

### ISSUE THREAD

**Issue by josago97** [jerry08/SpotifyExplode#3]
Hello, I have been trying to obtain the download url from the urls of the examples and it always returns null. I think Spotify has changed something and what is currently implemented is not working.

**Comment by jerry08** [comment]
I don't know why it's returning null for you. I just uploaded unit tests and it works fine. You can view the action logs [here](https://github.com/jerry08/SpotifyExplode/actions/runs/6648195661/job/18064858033).

**Comment by josago97** [comment]
I have downloaded the code and run the tests and it gives me an error (attached screenshot). I have also made the http post request with postman to see what happens and although the request returns a code 200, the content is an error (I also attach a screenshot).
![image](https://github.com/jerry08/SpotifyExplode/assets/26380095/b09618b2-cc7d-4a47-abae-a31a65ff6969)
![image](https://github.com/jerry08/SpotifyExplode/assets/26380095/f5389147-ed11-43d8-a647-9ea218f86ed4)

**Comment by jerry08** [comment]
It seems like both apis are not working for you. Instead of relying on various websites and apis to get the download URL, I should probably search YouTube, SoundCloud, etc. given the spotify track name and artist like in [spotify-downloader](https://github.com/spotDL/spotify-downloader).

**Comment by josago97** [comment]
Yes okay. However, weeks ago it was working correctly for me. Could it be that they have caught it in my country or continent? I reside in Spain.

**Comment by jerry08** [comment]
That could be the case. Either way, I'll work on a solution when I have some time.

**Comment by josago97** [comment]
Okay thanks

**Comment by adanvdo** [comment]
Have you made any progress on this? @jerry08 
Any way I can help?
